### ISSUE TITLE
Update finalize_mu_lam_bulk() in run_sand.py

### ISSUE THREAD

**Issue by rubensamarojr** [zeshunzong/warp-mpm#5]
Hi!

Probably, **mpm_solver.finalize_mu_lam()** should be replaced by **mpm_solver.finalize_mu_lam_bulk()** in

https://github.com/zeshunzong/warp-mpm/blob/442d2c41f0890d86a841769b6f6b3173ad9a1c9b/run_sand.py#L37

**Comment by supertan0204** [comment]
corrected, thanks for pointing out!
